[workspace]
members = ["crates/core", "crates/ffmpeg", "crates/cli"]
default-members = ["crates/cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
anyhow = "1"
tab5conv-core = { path = "crates/core" }
tab5conv-ffmpeg = { path = "crates/ffmpeg" }
