[package]
name = "tab5conv-ffmpeg"
description = "Runs Tab5-Media-Player conversions with the ffmpeg command"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tab5conv-core.workspace = true
