[package]
name = "tab5conv"
description = "Convert video files for Tab5-Media-Player"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
tab5conv-core.workspace = true
tab5conv-ffmpeg.workspace = true
